# Generated by Django 2.2.17 on 2024-09-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fingers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmsname', models.CharField(max_length=255)),
                ('keyword', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=255)),
            ],
        ),
    ]
