# Generated by Django 2.2.17 on 2024-09-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_fingers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finger_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
