# Generated by Django 2.2.17 on 2024-09-13 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_finger_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fingers',
            name='method',
        ),
    ]
