# Generated by Django 2.2.17 on 2024-09-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_remove_fingers_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='fingers',
            name='method',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
