# Generated by Django 2.2.17 on 2024-09-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_fingers_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=255)),
                ('selected_scans', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('results', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
