# Generated by Django 2.2.17 on 2024-09-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_scantask'),
    ]

    operations = [
        migrations.AddField(
            model_name='scantask',
            name='nuclei_custom_pocs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scantask',
            name='nuclei_option',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scantask',
            name='port_scan_ports',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scantask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
